### ISSUE TITLE
Running 2 game instances on one pc causes crash after exit

### ISSUE THREAD

**Issue by ximael** [matthiasbroske/ProximityChat-UnityPackage#1]
1) Run 2 game instances on one pc (one may be in an unity editor)
2) Connect to each other
3) Quit one
4) Stop the game in the editor or quit compiled
5) Crash
[Editor.log.txt](https://github.com/matthiasbroske/ProximityChat-UnityPackage/files/14269755/Editor.log.txt)

**Comment by matthiasbroske** [comment]
Thanks for making me aware of this issue!

I was able to recreate it in a fresh project with only 1 instance of Unity running using the `StudioVoiceEmitter` (the `CoreVoiceEmitter` appears to be unaffected).

I believe f8911aa should fix this by making the programmer instrument callback static so as to ensure FMOD can safely access unmanaged memory, as discussed [here](https://qa.fmod.com/t/crash-on-event-initialization-only-in-build/18613/14).
 
But let me know if that doesn't fix it for you!
