### ISSUE TITLE
Server voice is not working, client is ok

### ISSUE THREAD

**Issue by ximael** [matthiasbroske/ProximityChat-UnityPackage#2]
1) Run 2 game instances (on one pc or not)
2) Connect to each other

When client speaks, server can hear.
When server speaks, client can't hear.

This is in player's NetworkBehaviour Start:
_voiceNetworker.StartRecording();

**Comment by matthiasbroske** [comment]
Have you tried calling StartRecording() in the Update method? I'm not sure why it would make a difference but when I do something like the following I can hear both the client and the server.
```
using ProximityChat;
using UnityEngine;

public class PushToTalk : MonoBehaviour
{
    [SerializeField] private VoiceNetworker _voiceNetworker;
    
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.V))
            _voiceNetworker.StartRecording();
        else if (Input.GetKeyUp(KeyCode.V))
            _voiceNetworker.StopRecording();
    }
}
```
In another project using this package I support both push to talk and always on voice audio by doing something like this:
```
private void Update()
{
    if (!_pushToTalkEnabled || _inputManager.PushToTalkKeyDown)
        _voiceNetworker.StartRecording();
    else
        _voiceNetworker.StopRecording();
}
```
Since StartRecording() will exit early if it's already recording it's generally fine to call it every frame.

**Comment by ximael** [comment]
Yes, it was initially in my code. I haven't tried every frame.
```
private void Start()
    {
        AppSettingsManager.Instance.onUsePushToTalk += OnSetUsePushToTalk;
        _usePushToTalk = AppSettingsManager.Instance.appSettings.sound.usePushToTalk;
        OnSetUsePushToTalk(_usePushToTalk);
    }
private void Update()
    {
        if (!IsOwner) return;
        if (_usePushToTalk && Input.GetKeyDown(AppSettingsManager.Instance.appSettings.keybinds.pushToTalk))
        {
            _voiceNetworker.StartRecording();
        }
        else if (_usePushToTalk && Input.GetKeyUp(AppSettingsManager.Instance.appSettings.keybinds.pushToTalk))
        {
            _voiceNetworker.StopRecording();
        }
    }
public void OnSetUsePushToTalk(bool v)
    {
        _usePushToTalk = v;
        if (v) _voiceNetworker.StopRecording();
        else _voiceNetworker.StartRecording();
    }
```
Client works, server - doesn't.

Thanks for sharing this btw. This voice thing is quite complicated.

**Comment by ximael** [comment]
Actually, I can hear a voice, but it is very quiet.
I even _voiceNetworker.SetOutputVolume(1); in Update, no luck.

If I run 3 instances of the game, 1 host, 2 clients, only the last joined have a normal record voice volume.

**Comment by matthiasbroske** [comment]
Shoot, I'm struggling to recreate this issue on my end. Have you tried setting the output volume to something absurd for the sake of testing, say `_voiceNetworker.SetOutputVolume(10)`? Or maybe adjusting your mixer in FMOD could help increase the volume, though if it really is only affecting the last joined client then that is a bit odd. I'll investigate further when I get a chance.

**Comment by ximael** [comment]
If it was only in case of 2 instances on one pc, there might be some mic monopoly possibilities or something. But the same goes on different pcs.
The game is like Raft: host creates a game, then in any time clients can connect or disconnect.
Player's character is spawned manually with SpawnAsPlayerObject(clientId).
Seems like the problem with record volume, cause if I create 3 instances of a game, the last connected client can be heard well on another instances. But host or the 1st connected client are super quiet, when they are trying to talk.

**Comment by ximael** [comment]
Core version is working. IDK what could be wrong in the fmod project, just used the instructions.
I'll stay with core for now. Sorry for taking your time and thanks again.

**Comment by matthiasbroske** [comment]
No worries at all, and thanks for taking so much time to test this all out yourself as well! 

I'll see if I can figure out what's going on with the FMOD Studio version when I have a moment, but I'm glad to hear that core is working for now. In theory you can achieve all the same voice effects with core as with FMOD Studio it just requires some manual coding via the FMOD core engine API. I don't think I expose that functionality very well at the moment though so I can work on that, and also feel free to modify as necessary.

Let me know if you run into any other issues, and best of luck on your project!
